import fs from "fs";
import path from "path";

const projectRoot = process.cwd();
const assetRoot = path.resolve(projectRoot, process.argv[2] ?? "assets");
const outputStyle = path.resolve(projectRoot, "src/styles/asset-brightness-overrides.css");
const outputJson = path.resolve(projectRoot, "asset-brightness-report.json");
const outputMd = path.resolve(projectRoot, "asset-brightness-report.md");

const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"]);

const CATEGORY_RULES = [
  { test: /title|background|destination|travel/i, min: 0.34, boost: 1.18, contrast: 1.08, saturate: 1.06 },
  { test: /avatar|npc|crew|portrait/i, min: 0.38, boost: 1.22, contrast: 1.10, saturate: 1.08 },
  { test: /artifact|relic|item/i, min: 0.36, boost: 1.20, contrast: 1.12, saturate: 1.10 },
  { test: /ship|vessel/i, min: 0.35, boost: 1.18, contrast: 1.10, saturate: 1.06 },
  { test: /.*/i, min: 0.34, boost: 1.18, contrast: 1.08, saturate: 1.05 }
];

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (IMAGE_EXTS.has(path.extname(entry.name).toLowerCase())) out.push(p);
  }
  return out;
}

function categorize(file) {
  const rel = path.relative(projectRoot, file).replaceAll("\\", "/");
  return CATEGORY_RULES.find(rule => rule.test.test(rel)) ?? CATEGORY_RULES[CATEGORY_RULES.length - 1];
}

function cssEscapePath(rel) {
  return rel.replaceAll("\\", "/").replaceAll('"', '\\"');
}

/**
 * Browser-free brightness audit:
 * We cannot decode image pixels in a dependency-free Node script, so this script uses:
 * - file path category
 * - known dark-background UI thresholds
 * - filename/asset family defaults
 *
 * If the project later adds a decoder dependency such as sharp or jimp, this file can be extended to measure actual pixels.
 */
function estimateBrightness(file) {
  const rel = path.relative(projectRoot, file).replaceAll("\\", "/").toLowerCase();
  let score = 0.42;

  if (rel.includes("void") || rel.includes("black") || rel.includes("dark")) score -= 0.10;
  if (rel.includes("title") || rel.includes("background")) score -= 0.06;
  if (rel.includes("artifact") || rel.includes("relic")) score -= 0.03;
  if (rel.includes("avatar") || rel.includes("portrait")) score += 0.02;
  if (rel.includes("bright") || rel.includes("light") || rel.includes("aurora")) score += 0.06;
  if (rel.includes("eclipse") || rel.includes("shadow") || rel.includes("night")) score -= 0.08;

  return Math.max(0.05, Math.min(0.85, score));
}

function buildCss(results) {
  const dark = results.filter(r => r.needsBoost);

  const lines = [];
  lines.push("/* Star Ledger asset brightness overrides - generated by tools/auditAssetBrightness.mjs */");
  lines.push("/* Safe non-destructive image readability patch for dark UI backgrounds. */");
  lines.push("");
  lines.push(":root {");
  lines.push("  --sl-asset-brightness-default: 1.12;");
  lines.push("  --sl-asset-contrast-default: 1.06;");
  lines.push("}");
  lines.push("");

  lines.push("img[data-sl-asset], .sl-asset-image {");
  lines.push("  filter: brightness(var(--sl-asset-brightness-default)) contrast(var(--sl-asset-contrast-default));");
  lines.push("}");
  lines.push("");

  for (const r of dark) {
    lines.push(`img[src$="${cssEscapePath(r.relativePath)}"],`);
    lines.push(`[style*="${cssEscapePath(r.relativePath)}"] {`);
    lines.push(`  filter: brightness(${r.recommended.brightness}) contrast(${r.recommended.contrast}) saturate(${r.recommended.saturate}) !important;`);
    lines.push("}");
    lines.push("");
  }

  lines.push("/* UI card image guard: keeps encounter/crew/artifact images readable without blowing out text. */");
  lines.push(".encounter-card img, .crew-card img, .artifact-card img, .sl-encounter-card img, .sl-crew-card img, .sl-artifact-card img {");
  lines.push("  filter: brightness(1.16) contrast(1.08) saturate(1.05);");
  lines.push("}");
  lines.push("");

  lines.push("/* Title and full-screen backgrounds get a gentler lift to preserve atmosphere. */");
  lines.push(".title-screen::before, .title-screen-bg, .screen-background, .destination-background, .travel-background {");
  lines.push("  filter: brightness(1.10) contrast(1.06) saturate(1.04);");
  lines.push("}");

  return lines.join("\n");
}

function buildMd(results) {
  const dark = results.filter(r => r.needsBoost);
  const ok = results.length - dark.length;

  const lines = [];
  lines.push("# Star Ledger Asset Brightness Report");
  lines.push("");
  lines.push(`Total image assets scanned: ${results.length}`);
  lines.push(`Assets needing boost: ${dark.length}`);
  lines.push(`Assets acceptable: ${ok}`);
  lines.push("");
  lines.push("## Assets Needing Brightness Boost");
  lines.push("");
  if (!dark.length) {
    lines.push("None detected.");
  } else {
    for (const r of dark) {
      lines.push(`- ${r.relativePath}`);
      lines.push(`  - estimated brightness: ${r.estimatedBrightness}`);
      lines.push(`  - threshold: ${r.threshold}`);
      lines.push(`  - recommended filter: brightness(${r.recommended.brightness}) contrast(${r.recommended.contrast}) saturate(${r.recommended.saturate})`);
    }
  }
  lines.push("");
  lines.push("## Notes");
  lines.push("- This is a non-destructive code patch.");
  lines.push("- It boosts rendered images via CSS instead of modifying PNG/JPG/WebP files.");
  lines.push("- If you want true pixel-based auditing, add `sharp` or `jimp` and extend the estimator.");
  return lines.join("\n");
}

const files = walk(assetRoot);
const results = files.map(file => {
  const rule = categorize(file);
  const estimatedBrightness = Number(estimateBrightness(file).toFixed(3));
  const needsBoost = estimatedBrightness < rule.min;
  const relativePath = path.relative(projectRoot, file).replaceAll("\\", "/");

  return {
    file,
    relativePath,
    estimatedBrightness,
    threshold: rule.min,
    needsBoost,
    recommended: {
      brightness: needsBoost ? rule.boost : 1,
      contrast: needsBoost ? rule.contrast : 1,
      saturate: needsBoost ? rule.saturate : 1
    }
  };
});

fs.mkdirSync(path.dirname(outputStyle), { recursive: true });
fs.writeFileSync(outputStyle, buildCss(results), "utf8");
fs.writeFileSync(outputJson, JSON.stringify({ assetRoot, generatedAt: new Date().toISOString(), results }, null, 2), "utf8");
fs.writeFileSync(outputMd, buildMd(results), "utf8");

console.log(`Scanned ${results.length} image assets.`);
console.log(`Needs boost: ${results.filter(r => r.needsBoost).length}`);
console.log(`Wrote ${path.relative(projectRoot, outputStyle)}`);
console.log(`Wrote ${path.relative(projectRoot, outputJson)}`);
console.log(`Wrote ${path.relative(projectRoot, outputMd)}`);
